apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: graphite
  name: graphite
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graphite
    spec:
      containers:
      - image: graphiteapp/graphite-statsd
        name: graphite
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 2004
        - containerPort: 2023
        - containerPort: 2024
        - containerPort: 8125
          protocol: UDP
        - containerPort: 8126
        resources: {}
      restartPolicy: Always
status: {}
