apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jmxtrans
  name: jmxtrans
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jmxtrans
    spec:
      containers:
      - image: dalongrong/jmxtrans
        name: jmxtrans
        resources: {}
      restartPolicy: Always
status: {}
